# -*- coding: utf-8 -*-
"""Lab2_VigenereCipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z90pjolnrePS6nvQEYZduN0yvs_kuH8F
"""

import string
plaintext = ""
#key= "pascal"
key = input("Key: ")
#cipher = "hhwkswxslgntcg"
cipher = input("Cipher Text: ")
index = 0
for c in cipher:
  if c in string.ascii_lowercase:
    offset = ord(key[index]) -ord('a')
    positive_offset = 26 - offset

    decrypted_c = chr((ord(c) - ord('a') + positive_offset) % 26 + ord('a'))
    plaintext = plaintext + decrypted_c
    index = (index +1) % len(key)

  else:
    plaintext = plaintext + c

print(plaintext)