# -*- coding: utf-8 -*-
"""Lab4 Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mfheIIiwVYIrRrPx5-Q5x5BkPGFkGiwi
"""

PlainText = str(input("Please enter plain text: "))
Key = str(input("Please enter the Key: "))

#Encription
Encript_Text = [0 for i in range(len(PlainText))]
for i in range(len(PlainText)):
  Encript_Text[i] = int(PlainText[i]) ^ int(Key[i])
#Encript_Text = bin(int(PlainText^Key)).replace("0b","")
Encript_Text

#Decript
Decript_text = [0 for i in range(len(PlainText))]
for i in range(len(PlainText)):
  Decript_text[i] = int(Encript_Text[i]) ^ int(Key[i])
Decript_text